**This notebook is an exercise in the [SQL](https://www.kaggle.com/learn/intro-to-sql) course.  You can reference the tutorial at [this link](https://www.kaggle.com/dansbecker/getting-started-with-sql-and-bigquery).**

---

# Introduction

The first test of your new data exploration skills uses data describing crime in the city of Chicago.

Before you get started, run the following cell. It sets up the automated feedback system to review your answers.

In [20]:
# Set up feedack system
from learntools.core import binder
binder.bind(globals())
from learntools.sql.ex1 import *
print("Setup Complete")

Setup Complete

Use the next code cell to fetch the dataset.

In [21]:
from google.cloud import bigquery

# Create a "Client" object
client = bigquery.Client()

# Construct a reference to the "chicago_crime" dataset
dataset_ref = client.dataset("chicago_crime", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

Using Kaggle's public dataset BigQuery integration.

# Exercises

### 1) Count tables in the dataset

How many tables are in the Chicago Crime dataset?

In [22]:
# Write the code you need here to figure out the answer
# List all the tables in the "hacker_news" dataset
tables = list(client.list_tables(dataset))
# Print names of all tables in the dataset (there are four!)
for table in tables:  
    print(table.table_id)

crime

In [26]:
# List all the tables in the "chicago_crime" dataset
tables = list(client.list_tables(dataset))

num_tables = len(tables) # Store the answer as num_tables and then run this cell

# Check your answer
q_1.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [25]:
#q_1.hint()
q_1.solution()

Solution:
```python

# List all the tables in the "chicago_crime" dataset
tables = list(client.list_tables(dataset))

# Print number of tables in the dataset
print(len(tables))

num_tables = 1

```

### 2) Explore the table schema

How many columns in the `crime` table have `TIMESTAMP` data?

In [30]:
# Construct a reference to the "full" table
table_ref = dataset_ref.table("full")
# Construct a reference to the "crime" table
table_ref = dataset_ref.table("crime")

# API request - fetch the table
table = client.get_table(table_ref)

In [31]:
# Print information on all the columns in the "crime" table in the "chicago_crime" dataset
print(table.schema)

[SchemaField('unique_key', 'INTEGER', 'REQUIRED', 'Unique identifier for the record.', ()), SchemaField('case_number', 'STRING', 'NULLABLE', 'The Chicago Police Department RD Number (Records Division Number), which is unique to the incident.', ()), SchemaField('date', 'TIMESTAMP', 'NULLABLE', 'Date when the incident occurred. this is sometimes a best estimate.', ()), SchemaField('block', 'STRING', 'NULLABLE', 'The partially redacted address where the incident occurred, placing it on the same block as the actual address.', ()), SchemaField('iucr', 'STRING', 'NULLABLE', 'The Illinois Unifrom Crime Reporting code. This is directly linked to the Primary Type and Description. See the list of IUCR codes at https://data.cityofchicago.org/d/c7ck-438e.', ()), SchemaField('primary_type', 'STRING', 'NULLABLE', 'The primary description of the IUCR code.', ()), SchemaField('description', 'STRING', 'NULLABLE', 'The secondary description of the IUCR code, a subcategory of the primary description.', ()), SchemaField('location_description', 'STRING', 'NULLABLE', 'Description of the location where the incident occurred.', ()), SchemaField('arrest', 'BOOLEAN', 'NULLABLE', 'Indicates whether an arrest was made.', ()), SchemaField('domestic', 'BOOLEAN', 'NULLABLE', 'Indicates whether the incident was domestic-related as defined by the Illinois Domestic Violence Act.', ()), SchemaField('beat', 'INTEGER', 'NULLABLE', 'Indicates the beat where the incident occurred. A beat is the smallest police geographic area â€“ each beat has a dedicated police beat car. Three to five beats make up a police sector, and three sectors make up a police district. The Chicago Police Department has 22 police districts. See the beats at https://data.cityofchicago.org/d/aerh-rz74.', ()), SchemaField('district', 'INTEGER', 'NULLABLE', 'Indicates the police district where the incident occurred. See the districts at https://data.cityofchicago.org/d/fthy-xz3r.', ()), SchemaField('ward', 'INTEGER', 'NULLABLE', 'The ward (City Council district) where the incident occurred. See the wards at https://data.cityofchicago.org/d/sp34-6z76.', ()), SchemaField('community_area', 'INTEGER', 'NULLABLE', 'Indicates the community area where the incident occurred. Chicago has 77 community areas. See the community areas at https://data.cityofchicago.org/d/cauq-8yn6.', ()), SchemaField('fbi_code', 'STRING', 'NULLABLE', "Indicates the crime classification as outlined in the FBI's National Incident-Based Reporting System (NIBRS). See the Chicago Police Department listing of these classifications at http://gis.chicagopolice.org/clearmap_crime_sums/crime_types.html.", ()), SchemaField('x_coordinate', 'FLOAT', 'NULLABLE', 'The x coordinate of the location where the incident occurred in State Plane Illinois East NAD 1983 projection. This location is shifted from the actual location for partial redaction but falls on the same block.', ()), SchemaField('y_coordinate', 'FLOAT', 'NULLABLE', 'The y coordinate of the location where the incident occurred in State Plane Illinois East NAD 1983 projection. This location is shifted from the actual location for partial redaction but falls on the same block.', ()), SchemaField('year', 'INTEGER', 'NULLABLE', 'Year the incident occurred.', ()), SchemaField('updated_on', 'TIMESTAMP', 'NULLABLE', 'Date and time the record was last updated.', ()), SchemaField('latitude', 'FLOAT', 'NULLABLE', 'The latitude of the location where the incident occurred. This location is shifted from the actual location for partial redaction but falls on the same block.', ()), SchemaField('longitude', 'FLOAT', 'NULLABLE', 'The longitude of the location where the incident occurred. This location is shifted from the actual location for partial redaction but falls on the same block.', ()), SchemaField('location', 'STRING', 'NULLABLE', 'The location where the incident occurred in a format that allows for creation of maps and other geographic operations on this data portal. This location is shifted from the actual location for partial redaction but falls on the same block.', ())]

In [32]:
num_timestamp_fields = 2 # Put your answer here

# Check your answer
q_2.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [33]:
#q_2.hint()
#q_2.solution()

### 3) Create a crime map

If you wanted to create a map with a dot at the location of each crime, what are the names of the two fields you likely need to pull out of the `crime` table to plot the crimes on a map?

In [ ]:
# Write the code here to explore the data so you can find the answer

In [35]:
fields_for_plotting = ['latitude', 'longitude'] # Put your answers here

# Check your answer
q_3.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [36]:
#q_3.hint()
#q_3.solution()

Thinking about the question above, there are a few columns that appear to have geographic data. Look at a few values (with the `list_rows()` command) to see if you can determine their relationship.  Two columns will still be hard to interpret. But it should be obvious how the `location` column relates to `latitude` and `longitude`.

In [37]:
# Scratch space for your code
df5= client.list_rows(table, max_results=5).to_dataframe()

In [38]:
df5

,unique_key,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
0,11637700,JC203045,2018-11-28 09:00:00+00:00,032XX S WELLS ST,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,APARTMENT,False,False,...,11,34,26,None,None,2018,2019-03-29 16:12:07+00:00,None,None,None
1,10367905,HZ103719,2014-11-03 09:00:00+00:00,063XX N CENTRAL AVE,1120,DECEPTIVE PRACTICE,FORGERY,BANK,False,False,...,45,12,10,None,None,2014,2016-01-07 16:14:34+00:00,None,None,None
2,5307072,HM721055,2006-11-14 22:47:44+00:00,059XX N CICERO AVE,2022,NARCOTICS,POSS: COCAINE,OTHER,True,False,...,39,12,18,None,None,2006,2015-08-17 15:03:40+00:00,None,None,None
3,7781803,HS587766,2009-08-01 00:00:00+00:00,071XX W DEVON AVE,1751,OFFENSE INVOLVING CHILDREN,CRIM SEX ABUSE BY FAM MEMBER,RESIDENCE,True,True,...,41,10,20,None,None,2009,2015-08-17 15:03:40+00:00,None,None,None
4,2353734,HH639874,2002-09-10 22:00:00+00:00,095XX S EWING AVE,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,PARK PROPERTY,True,False,...,10,52,02,None,None,2002,2015-08-17 15:03:40+00:00,None,None,None

In [39]:
# let see 10000 data point
df=client.list_rows(table, max_results=10000).to_dataframe()

In [40]:
df.tail()

,unique_key,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
9995,11730544,JC315868,2019-06-21 15:13:00+00:00,092XX S DOBSON AVE,1661,GAMBLING,GAME/DICE,SIDEWALK,True,False,...,8.0,47,19,1184832.0,1843876.0,2019,2019-06-30 15:56:27+00:00,41.726752,-87.598529,"(41.726752448, -87.598529034)"
9996,11683848,JC259075,2016-02-19 21:00:00+00:00,061XX N MILWAUKEE AVE,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,ALLEY,False,False,...,39.0,10,02,NaN,NaN,2016,2019-07-04 16:09:46+00:00,NaN,NaN,None
9997,11764110,JC356357,2019-07-19 23:55:00+00:00,010XX E 93RD ST,051B,ASSAULT,AGGRAVATED: OTHER FIREARM,STREET,False,False,...,8.0,47,04A,1184682.0,1843523.0,2019,2019-07-26 16:10:46+00:00,41.725787,-87.599090,"(41.725787289, -87.599089524)"
9998,11774104,JC368520,2019-07-28 17:30:00+00:00,051XX S KOSTNER AVE,0496,BATTERY,AGGRAVATED DOMESTIC BATTERY: KNIFE/CUTTING INST,SIDEWALK,False,True,...,23.0,57,04B,1147899.0,1870176.0,2019,2019-08-09 16:09:21+00:00,41.799710,-87.733148,"(41.799709656, -87.733147792)"
9999,11778826,JC373952,2019-07-31 18:30:00+00:00,011XX E 83RD ST,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,STREET,False,False,...,8.0,45,26,1185421.0,1850194.0,2019,2019-08-07 16:07:50+00:00,41.744076,-87.596173,"(41.744075903, -87.596173259)"

In [41]:
df.shape

(10000, 22)

---




*Have questions or comments? Visit the [Learn Discussion forum](https://www.kaggle.com/learn-forum/161314) to chat with other Learners.*